blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_post_view:
    path:     /post/{id}
    defaults: { _controller: BlogBundle:Post:view }
    requirements:
        id: \d+

blog_category_view:
    path: /category/{name}
    defaults: { _controller: BlogBundle:Category:show }
    requirements:
        name: .+

blog_category_list:
    path: /category/
    defaults: { _controller: BlogBundle:Category:list }

