admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_dashboard:
    path: /dashboard/
    defaults: { _controller: AdminBundle:Default:dashboard }

admin_menuitem:
    path: /menuitem/
    defaults: { _controller: AdminBundle:MenuItem:index }

# ... Admin Blog
admin_blog_post:
    path:     /blog/post/{id}
    defaults: { _controller: AdminBundle:Blog/AdminPost:index, id: null }
    requirements:
      id: \d+

admin_blog_post_delete:
    path: /blog/post/{id}/delete
    defaults: { _controller: AdminBundle:Blog/AdminPost:delete }
    requirements:
      id: \d+

admin_blog_category:
    path: /blog/category/{id}
    defaults: { _controller: AdminBundle:Blog/AdminCategory:index, id: null}
    requirements:
      id: \d+

admin_blog_category_delete:
    path: /blog/category/{id}/delete
    defaults: { _controller: AdminBundle:Blog/AdminCategory:delete }
    requirements:
      id: \d+