admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_dashboard:
    path: /dashboard/
    defaults: { _controller: AdminBundle:Default:dashboard }

admin_menuitem:
    path: /menuitem/
    defaults: { _controller: AdminBundle:MenuItem:index }

# ... Admin Blog
admin_blog_post:
    path:     /blog/post/{id}
    defaults: { _controller: AdminBundle:AdminPost:index, id: null }
    requirements:
      id: \d+

admin_blog_post_delete:
    path: /blog/post/{id}/delete
    defaults: { _controller: AdminBundle:AdminPost:delete }
    requirements:
      id: \d+
